package com.michaelb.nucleus.models;

public enum Major {
    ACCOUNTING("Accounting"),
    AFRICANA_STUDIES("Africana Studies"),
    ARAB_AND_ISLAMIC_STUDIES("Arab And Islamic Studies"),
    ART_HISTORY("Art History"),
    ASIAN_STUDIES("Asian Studies"),
    ASTRONOMY_AND_ASTROPHYSICS("Astronomy And Astrophysics"),
    BIOCHEMISTRY("Biochemistry"),
    BIOLOGY("Biology"),
    BIOMEDICAL_ENGINEERING("Biomedical Engineering"),
    BUSINESS_ANALYTICS("Business Analytics"),
    CHEMICAL_ENGINEERING("Chemical Engineering"),
    CHEMISTRY("Chemistry"),
    CHINESE_STUDIES("Chinese Studies"),
    CIVIL_ENGINEERING("Civil Engineering"),
    CLASSICAL_STUDIES("Classical Studies"),
    COGNITIVE_AND_BEHAVIORAL_NEUROSCIENCE("Cognitive And Behavioral Neuroscience"),
    COMMUNICATION("Communication"),
    COMPREHENSIVE_SCIENCE("Comprehensive Science"),
    COMPUTER_ENGINEERING("Computer Engineering"),
    COMPUTER_SCIENCE("Computer Science"),
    CRIMINOLOGY("Criminology"),
    CULTURAL_STUDIES("Cultural Studies"),
    DENTAL_MEDICINE("Dental Medicine"),
    ECONOMICS("Economics"),
    EDUCATION("Education"),
    ELECTRICAL_ENGINEERING("Electrical Engineering"),
    ENGLISH("English"),
    ENTREPRENEURSHIP("Entrepreneurship"),
    ENVIRONMENTAL_SCIENCE("Environmental Science"),
    ENVIRONMENTAL_STUDIES("Environmental Studies"),
    FINANCE("Finance"),
    FRENCH_AND_FRANCOPHONE_STUDIES("French And Francophone Studies"),
    GENDER_AND_WOMENS_STUDIES("Gender and Women's Studies"),
    GENERAL_STUDIES("General Studies"),
    GEOGRAPHY("Geography"),
    GLOBAL_INTERDISCIPLINARY_STUDIES("Global Interdisciplinary Studies"),
    HISTORY("History"),
    HUMAN_RESOURCE_MANAGEMENT("Human Resource Management"),
    HUMANITIES("Humanities"),
    INDIVIDUALLY_DESIGNED_MAJOR("Individually Designed Major"),
    INFORMATION_SYSTEMS_AND_TECHNOLOGY("Information Systems And Technology"),
    INTERNATIONAL_BUSINESS("International Business"),
    IRISH_STUDIES("Irish Studies"),
    ITALIAN("Italian"),
    JAPANESE_STUDIES("Japanese Studies"),
    LATIN_AMERICAN_STUDIES("Latin American Studies"),
    LEADERSHIP("Leadership"),
    LIBERAL_ARTS("Liberal Arts"),
    MANAGEMENT("Management"),
    MANAGEMENT_INFORMATION_SYSTEMS("Management Information Systems"),
    MARKETING("Marketing"),
    MATHEMATICS("Mathematics"),
    MECHANICAL_ENGINEERING("Mechanical Engineering"),
    NURSING("Nursing"),
    OPTOMETRY("Optometry"),
    ORGANIZATIONAL_DEVELOPMENT_AND_MANAGEMENT("Organizational Development And Management"),
    OSTEOPATHIC_MEDICINE("Osteopathic Medicine"),
    PEACE_AND_JUSTICE("Peace and Justice"),
    PHILOSOPHY("Philosophy"),
    PHYSICS("Physics"),
    POLITICAL_SCIENCE("Political Science"),
    PSYCHOLOGY("Psychology"),
    PUBLIC_ADMINISTRATION("Public Administration"),
    PUBLIC_SERVICE_AND_ADMINISTRATION("Public Service And Administration"),
    REAL_ESTATE("Real Estate"),
    RUSSIAN_AREA_STUDIES("Russian Area Studies"),
    SOCIOLOGY("Sociology"),
    SPANISH_STUDIES("Spanish Studies"),
    STATISTICS("Statistics"),
    THEOLOGY_AND_RELIGIOUS_STUDIES("Theology And Religious Studies");

    private final String displayName;

    Major(String displayName) {
        this.displayName = displayName;
    }

    @Override
    public String toString() {
        return displayName;
    }
}